openapi: 3.0.3
info:
  description: |
    This is the backend APIs for a chat application.
  version: "1.0.0"
  title: Parley
  termsOfService: 'https://swagger.io/terms/'
  contact:
    email: jrackliff@gmail.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: http://localhost:8080/parley-api
    description: Local server
  - url: https://virtserver.swaggerhub.com/JRACKLIFF/Parley2/1.0.0
    description: SwaggerHub API Auto Mocking
  - url: https://k0000.company.net/parley-api
    description: Production server
tags:
  - name: User
    description: Operations about user
  - name: ChatMessage
    description: These are the chat messages by a user in a chat room
  - name: ChatRoom
    description: Operations about chat rooms.
  - name: Enrollment
    description: Operations about enrolling users in chat rooms

paths:
  # Authentication
  /auth/login:
    $ref: './openapi/paths/auth.yaml#/paths/~1auth~1login'

  # User paths
  ########################################################################################
  # IMPORTANT
  #  The ~1 is used because forward slashes / can't be used directly in JSON references,
  #  so they're encoded as ~1. This is part of the JSON Pointer specification that
  # OpenAPI uses for references.
  #
  #  /paths/~1chatrooms~1{id}: The internal path within chatroom.yaml
  #  /paths points to the paths object in the YAML
  #  ~1 is the URL-encoded form of /
  #
  #  So ~1chatrooms~1{id} actually means
  #  /chatrooms/{id}
  ########################################################################################

  /users:
    $ref: './openapi/paths/user.yaml#/paths/~1users'
  /users/{id}:
    $ref: './openapi/paths/user.yaml#/paths/~1users~1{id}'
  /users/{id}/avatar:
    $ref: './openapi/paths/user.yaml#/paths/~1users~1{id}~1avatar'
  /users/{userId}/chatrooms:
    $ref: './openapi/paths/user.yaml#/paths/~1users~1{userId}~1chatrooms'

  # Chat paths
  /chats:
    $ref: './openapi/paths/chatmessage.yaml#/paths/~1chats'
  /chats/{id}:
    $ref: './openapi/paths/chatmessage.yaml#/paths/~1chats~1{id}'

  # Chatroom paths
  /chatrooms:
    $ref: './openapi/paths/chatroom.yaml#/paths/~1chatrooms'
  /chatrooms/{id}:
    $ref: './openapi/paths/chatroom.yaml#/paths/~1chatrooms~1{id}'
  /chatrooms/{id}/icon:
    $ref: './openapi/paths/chatroom.yaml#/paths/~1chatrooms~1{id}~1icon'
  /chatrooms/{chatRoomId}/chats:
    $ref: './openapi/paths/chatroom.yaml#/paths/~1chatrooms~1{chatRoomId}~1chats'

  # Enrollment paths
  /enrollments:
    $ref: './openapi/paths/enrollment.yaml#/paths/~1enrollments'
  /enrollments/{chatRoomId}:
    $ref: './openapi/paths/enrollment.yaml#/paths/~1enrollments~1{chatRoomId}'
  /enrollments/{chatRoomId}/users/{userId}:
    $ref: './openapi/paths/enrollment.yaml#/paths/~1enrollments~1{chatRoomId}~1users~1{userId}'

components:
  schemas:
    # Auth schemas
    AuthRequest:
      $ref: './openapi/schemas/auth.yaml#/AuthRequest'
    AuthResponse:
      $ref: './openapi/schemas/auth.yaml#/AuthResponse'

    # User schemas
    User:
      $ref: './openapi/schemas/user.yaml#/User'
    NewUser:
      $ref: './openapi/schemas/user.yaml#/NewUser'

    # Chat schemas
    ChatMessage:
      $ref: './openapi/schemas/chatmessage.yaml#/ChatMessage'
    NewChatMessage:
      $ref: './openapi/schemas/chatmessage.yaml#/NewChatMessage'

    # Chatroom schemas
    ChatRoom:
      $ref: './openapi/schemas/chatroom.yaml#/ChatRoom'
    NewChatRoom:
      $ref: './openapi/schemas/chatroom.yaml#/NewChatRoom'

    # Enrollment schemas
    Enrollment:
      $ref: './openapi/schemas/enrollment.yaml#/Enrollment'
    NewEnrollment:
      $ref: './openapi/schemas/enrollment.yaml#/NewEnrollment'

    # Common schemas
    Error:
      $ref: './openapi/schemas/common.yaml#/Error'

  securitySchemes:
    bearerAuth:
      $ref: './openapi/security/security.yaml#/bearerAuth'